import torch

LABEL_INNER_BUFFER = 1
LABEL_OUTER_BUFFER = 1

TILES_LIN = 6
TILES_COL = 3
TILES_VALIDATION = [0, 2, 7, 9, 12, 13] 

BATCH_SIZE = 32

PATCH_SIZE = 128
PATCH_OVERLAP = 0.8

MIN_DEFORESTATION = 0.02

N_TRAIN_MODELS = 10
LEARNING_RATE = 1e-4
CLASS_WEIGHTS = [0.1, 0.9, 0]

N_MAX_EPOCHS = 500
EPOCHS = 50

LEARNING_RATE = 1e-4


DEFORESTATION_PATCHES_PREFIX = 'patches'
NO_DEFORESTATION_PATCHES_PREFIX = 'c_patches'
PREVIOUS_PREFIX = 'previous_def'
LABEL_PREFIX = 'label'